<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-11T14:03:55 GMT" name="Default suite" finished-at="2024-01-11T14:03:55 GMT" duration-ms="200">
    <groups>
      <group name="SMOKETEST">
        <method signature="TestNGLearning.TestNGSample()[pri:-1, instance:TestNG.TestNGLearning@3d6f0054]" name="TestNGSample" class="TestNG.TestNGLearning"/>
      </group> <!-- SMOKETEST -->
    </groups>
    <test started-at="2024-01-11T14:03:55 GMT" name="Default test" finished-at="2024-01-11T14:03:55 GMT" duration-ms="200">
      <class name="TestNG.TestNGLearning">
        <test-method signature="TestNGSample()[pri:-1, instance:TestNG.TestNGLearning@3d6f0054]" started-at="2024-01-11T14:03:55 GMT" name="TestNGSample" finished-at="2024-01-11T14:03:55 GMT" duration-ms="25" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNGSample -->
        <test-method signature="TestNGSample()[pri:-1, instance:TestNG.TestNGLearning@3d6f0054]" started-at="2024-01-11T14:03:55 GMT" name="TestNGSample" finished-at="2024-01-11T14:03:55 GMT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNGSample -->
        <test-method signature="TestNGSample()[pri:-1, instance:TestNG.TestNGLearning@3d6f0054]" started-at="2024-01-11T14:03:55 GMT" name="TestNGSample" finished-at="2024-01-11T14:03:55 GMT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNGSample -->
        <test-method signature="TestNGSample2()[pri:1, instance:TestNG.TestNGLearning@3d6f0054]" started-at="2024-01-11T14:03:55 GMT" name="TestNGSample2" depends-on-groups="SMOKETEST" finished-at="2024-01-11T14:03:55 GMT" depends-on-methods="TestNG.TestNGLearning.TestNGSample" duration-ms="70" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestNGLearning.TestNGSample2()[pri:1, instance:TestNG.TestNGLearning@3d6f0054] should have thrown an exception of type class java.util.concurrent.TimeoutException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestNGLearning.TestNGSample2()[pri:1, instance:TestNG.TestNGLearning@3d6f0054] should have thrown an exception of type class java.util.concurrent.TimeoutException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNGSample2 -->
      </class> <!-- TestNG.TestNGLearning -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
